aufs support.
git-svn-id: https://eden-linux.googlecode.com/svn@61 5ec893c4-3adc-f636-74ed-cb0741876729

diff --git a/EdenLinux/tmpl/packages/bootscripts/etc/init.d/mountroot b/EdenLinux/tmpl/packages/bootscripts/etc/init.d/mountroot
--- a/EdenLinux/tmpl/packages/bootscripts/etc/init.d/mountroot
+++ b/EdenLinux/tmpl/packages/bootscripts/etc/init.d/mountroot
@@ -8,22 +8,26 @@
 . /etc/init.d/functions
 case "$1" in
 start)
-	echo "Mounting root file system in read-only mode."
-	check_status
-	mount -n -o remount,ro /
-	
-	echo "Checking root filesystem."
-	/sbin/fsck -p -T /
-	if [ "$?" -gt "1" ]; then
-		echo "WARNING: Errors found while checking root filesystem."
-		echo "You can login as root now, the system will reboot after logout."
-		sulogin
-		reboot
+	if [ -e "/etc/EdenLive" ]; then
+		echo "Not checking read-only filesystem"
+	else	
+		echo "Mounting root file system in read-only mode."
+		mount -n -o remount,ro /
+		check_status
+		
+		echo "Checking root filesystem."
+		/sbin/fsck -p -T /
+		if [ "$?" -gt "1" ]; then
+			echo "WARNING: Errors found while checking root filesystem."
+			echo "You can login as root now, the system will reboot after logout."
+			sulogin
+			reboot
+		fi
+		
+		echo -n "Remounting root in read-write mode: "
+		mount -n -o remount,rw /
+		check_status
 	fi
-	
-	echo -n "Remounting root in read-write mode: "
-	mount -o remount,rw /
-	check_status
 	;;
 stop)
 	echo -n "Unmounting root"
diff --git a/EdenLinux/tmpl/packages/udev/udev b/EdenLinux/tmpl/packages/udev/udev
--- a/EdenLinux/tmpl/packages/udev/udev
+++ b/EdenLinux/tmpl/packages/udev/udev
@@ -12,8 +12,10 @@ start)
 
 	/bin/mount -n -t tmpfs -o mode=0755 udev /dev
 
-	[ -d /lib/udev/devices ] && cp -af /lib/udev/devices/* /dev
-
+	if [ -d /lib/udev/devices ] ; then
+		cp -af /lib/udev/devices/* /dev
+	fi
+	
 	if [ ! -d /dev/shm ] ; then
 		mkdir /dev/shm || die "failed to mkdir /dev/shm"
 	fi
@@ -23,6 +25,10 @@ start)
 	echo > /proc/sys/kernel/hotplug
 
 	dmesg -n 2
+	
+	if [ ! -d /run ] ; then
+		mkdir /run || die "failed to mkdir /run"
+	fi
 
 	/sbin/udevd --daemon
 	check_status
@@ -33,6 +39,16 @@ start)
 	/sbin/udevadm trigger
 	/sbin/udevadm settle
 	dmesg -n 7
+	check_status
+	
+	echo -n "Mounting devpts: "
+	mkdir /dev/pts
+	mount -t devpts devpts /dev/pts 
+	check_status
+	;;
+stop)
+	echo -n "Stopping udev: "
+	/sbin/udevadm control --exit
 	check_status
 	;;
 *)
