Added python, and initscripts in early alpha. Boots and uses udev to create devices. No network yet.
git-svn-id: https://eden-linux.googlecode.com/svn@41 5ec893c4-3adc-f636-74ed-cb0741876729

diff --git a/EdenLinux/conf/packages/bootscripts/etc/init.d/mountroot b/EdenLinux/conf/packages/bootscripts/etc/init.d/mountroot
--- a/EdenLinux/conf/packages/bootscripts/etc/init.d/mountroot
+++ b/EdenLinux/conf/packages/bootscripts/etc/init.d/mountroot
@@ -1,21 +1,36 @@
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          mountroot      
+# Short-Description: Check and mount the root filesystem
+# Required-Start:	 udev
+### END INIT INFO
+
 . /etc/init.d/functions
-
-echo "Starting fsck for root filesystem."
-/sbin/fsck -T -C /
-if [ "$?" -gt 2 ]; then
-	echo "WARNING: Errors found while checking root filesystem."
-	echo "You can login as root now, the system will reboot after logout."
-	sulogin
-	reboot
-elif [ "$?" = "2" ]; then
-	echo "NOTICE: System needsto be rebooted now."
-	sleep 1
-	reboot
-else
-	echo -n "Checking root filesystem: "
+case "$1" in
+start)
+	echo "Mounting root file system in read-only mode."
 	check_status
-fi
-
-echo -n "Remounting root rw: "
-mount -o remount,rw /
-check_status
+	mount -n -o remount,ro /
+	
+	echo "Checking root filesystem."
+	/sbin/fsck -p -T /
+	if [ "$?" -gt "1" ]; then
+		echo "WARNING: Errors found while checking root filesystem."
+		echo "You can login as root now, the system will reboot after logout."
+		sulogin
+		reboot
+	fi
+	
+	echo -n "Remounting root in read-write mode: "
+	mount -o remount,rw /
+	check_status
+	;;
+stop)
+	echo -n "Unmounting root"
+	umount /
+	check_status
+	;;
+*)
+	echo "Usage: $0 {start|stop|restart}"
+	exit 1
+esac
diff --git a/EdenLinux/conf/packages/udev/udev b/EdenLinux/conf/packages/udev/udev
--- a/EdenLinux/conf/packages/udev/udev
+++ b/EdenLinux/conf/packages/udev/udev
@@ -1,9 +1,10 @@
-#!/bin/ash
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          udev      
+# Short-Description: Dynamic devices 
+### END INIT INFO
 
-# udev Startup Script
-#
-
-. /etc/rc.d/init.d/functions
+. /etc/init.d/functions
 
 case "$1" in
 start)
@@ -11,19 +12,27 @@ start)
 
 	/bin/mount -n -t tmpfs -o mode=0755 udev /dev
 
-	cp -aR /lib/udev/devices/* /dev
-	
+	[ -d /lib/udev/devices ] && cp -af /lib/udev/devices/* /dev
+
+	if [ ! -d /dev/shm ] ; then
+		mkdir /dev/shm || die "failed to mkdir /dev/shm"
+	fi
+
 	chmod 1777 /dev/shm
 
 	echo > /proc/sys/kernel/hotplug
 
-	/sbin/udevd --daemon
+	dmesg -n 2
 
+	/sbin/udevd --daemon
+	check_status
+	
 	mkdir -p /dev/.udev/queue
 
+	echo -n "Waiting for devices to settle"
 	/sbin/udevadm trigger
-	
 	/sbin/udevadm settle
+	dmesg -n 7
 	check_status
 	;;
 *)
